name: Code Analysis

on: [push, pull_request]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Code Analysis
      uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: pylint

  check-results:
    runs-on: ubuntu-latest

    needs: code-analysis

    steps:
    - name: Check Code Analysis Results
      run: echo "Check the code analysis results"
